### ISSUE TITLE
IL: Add partner bill ID (ie, bill ID from other chamber)

### ISSUE THREAD

**Issue by mileswwatkins** [openstates/openstates-scrapers#1666]
Recommended by @jonrogoff and @justgosh. Do either of you know where to get this alternate ID, when scraping a bill's webpage?

Once identified, the alternate ID should be stored in the `alternate_bill_ids` list property of the `Bill` object.

**Comment by jonrogoff** [comment]
I haven't come across anything definitive.  Hopefully, we can find something better than matching on bill title and summary.

**Comment by jamesturk** [comment]
closing this for now, no source seems apparent, looking at a handful of bills that have gone through the full legislative process, IL doesn't seem to list partner bills.  if someone in IL or otherwise interested can find some examples, we'd reconsider but as-is we can't provide what the state doesn't
